# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19f3f093c33de3c9428c7875ae1ec641"
name = "trade-shaker-doors"
application_url = "https://dfhw7q5aon9cu.cloudfront.net"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Required for draft orders and customers
scopes = "read_customers,read_draft_orders,write_customers,write_draft_orders,read_products,write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "https://dfhw7q5aon9cu.cloudfront.net/api/auth/callback",
  "https://5w1ympun8e.execute-api.eu-west-2.amazonaws.com/api/auth/callback",
  "http://localhost:5000/api/auth/callback",
  "http://127.0.0.1:5000/api/auth/callback"
]
